language: node_js
node_js: stable
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - npm run lint
  - xvfb-run polymer test --module-resolution=node --npm --plugin local
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test
    --module-resolution=node --npm --plugin sauce --job-name
    "cookies-list-items:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
    fi
env:
  global:
    - secure: >-
        k2GynM6kv87t9Kly9TU1ksI4NKCFW4t4tTKwxq8wZF3wlEq+MPAAiJNwwluCvu+kR5uvYOhUQMjJZvpWFyACbJwvtfecpqnyYsHAIC/JGAwL36WfaFHInojtj7YQKbHGJwi3wy4dccZ6Er5NZWFRYNmSV+tzin/QS6Kx9DCRWSgptYqu9jHOzt5nHEl3Ik8H7dJF2baqzqHC6IuX+4K1ks/+fxlYczSaLDdRZQ9M1/OxOqrmfSSu3RjelIEINhBwTLW9kNzegB/5oC9A5mcWfAujRiCI5nVB9iDufzR1FFL+Sv/o8mWbcGG5QCim1nK1WwnaKHd5TtWb3FoWD5QjJ91Pt8rcZIW5cTzagrvnKHT49iSrzAwT+doieYAyIzDFUQnZRUkV7eEWEuriN66NraCnm+t17FeBM1se8Rb5f06zEOr7mj2GaiRaDQlAo41DTk51MyUTuXbw4psgO/9SmmqCkBDpKppX/ahF5juB+gl5GdNF9sGDdCfSSxK+XssnwzE7bjzr1sZ+7UFlA4AQYKFu4kHowlHBKvwqin4mXvD6+liDE0YeQ60kUj47L1x1ey47E9xEfAo0ctFFnVLhe01kkw769NTJPeFxGpC/xrdNmfP1sA7ObB+kQSJQ20oTjtVgVAiOnrSasjh8uRycdHsu3isSWy+UFTh0KJBRaAM=
    - secure: >-
        iTssW+71DrmHBy6TgkwVc3yxpZtGe5Lz/lBdjC6DrsomyIhUs3ly30k5+3wkP5acS2FfUAlkKhUg3cHHPgcfHxWKeKUzqB98k56zBCJAgRPB8keKUumzYUwojwDeRsShxk/X2o6ZWC6zC1T+mYcMcG0VbI8hhCbIo1MW6VZu+U3yk9VPyg6AYhd7ZYKUxJPFGHxFBGn255fz6r3lTwo8hVstSpL8DQXdPibmDLwgea7jXpw98jGWhGVCB2jFkRcyUVid1+2otc8AUAXDOIFVvo3CR4gkBnuwY+F2FfRKdPGVDo5OhNd5D6H1yPxjEEMxmhtqYfpIMYr5wG852Nk+1rv85VrZIY+ETHKPrbNkzrr3JoeEQdtqArkBbzv9LnzzXGi7vjtXWIxFEvyxoWxeW+lozhLhCnQKB/y8xq1QE6NVcWJtL8IfILVwLPzb928vu6GefrGYjvp3nz2ztNBP3tjYhx/Y0Ucng9Y40p4hLMVm5F7sWa2cSi8/peovtsoOQKRdhj1laYxbcRh554oUmTDyAqsUQ9/RMywe66UVHUmZXl3dAN949HwR0Oy/qyO7WdPsiLFkxYnUr120YBT/V2v5sbACYtv2DlGMppi5Uv7pS5vJe5JBfuSTtgzOg56jvYRBVp1pWAtikvMt2czKyzhy/i2mU+ishKI8kv4JZ0w=
