/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cookies-list-items.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {CookiesListItems, CookiesListWrapper} from './src/CookiesListItems.js';
